version: '3.8'

services:
  chatbot_api:
    container_name: chatbot_voice
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app:rw